### ISSUE TITLE
How to setup Authware

### ISSUE THREAD

**Issue by bugrevealingbme** [AuthwareCloud/openvpn-setup-script#1]
This script give me The secret for the Authware setup is but i don't understand. How to set password?

**Comment by dnlib** [comment]
Hey there!

This script is designed to setup VPN servers with our OpenVPN authentication system.

**You must have a plan with us** in-order to use this system, plus the system is in active development and not functional.

Check out the link in the repository description or `README` file and you can find the **original link** to setup the **system without authentication.**

**Comment by dnlib** [comment]
I'm going to close this issue, as it's been inactive for just over a week.
